// should be included only in fldraw.cc

static void boxtypeDrawFunction(uchar n, int x, int y, int w, int h, Fl_Color color);

#define BOXTYPE_DRAW_FUNCTION_PROTO(n) \
static void boxtypeDrawFunction##n(int x, int y, int w, int h, Fl_Color color);

typedef struct {
    int            luaRef;
    Fl_Box_Draw_F* func;
    lua_State*     L;
} Boxtype_FunctionRef; // see table boxtype_FunctionRefs below

#define BOXTYPE_DRAW_FUNCTION_IMPL(n) \
static void boxtypeDrawFunction##n(int x, int y, int w, int h, Fl_Color color) \
    { \
    boxtypeDrawFunction(1##n - 1000, x, y, w, h, color); \
    } 

// Prototypes {
BOXTYPE_DRAW_FUNCTION_PROTO(000)
BOXTYPE_DRAW_FUNCTION_PROTO(001)
BOXTYPE_DRAW_FUNCTION_PROTO(002)
BOXTYPE_DRAW_FUNCTION_PROTO(003)
BOXTYPE_DRAW_FUNCTION_PROTO(004)
BOXTYPE_DRAW_FUNCTION_PROTO(005)
BOXTYPE_DRAW_FUNCTION_PROTO(006)
BOXTYPE_DRAW_FUNCTION_PROTO(007)
BOXTYPE_DRAW_FUNCTION_PROTO(008)
BOXTYPE_DRAW_FUNCTION_PROTO(009)
BOXTYPE_DRAW_FUNCTION_PROTO(010)
BOXTYPE_DRAW_FUNCTION_PROTO(011)
BOXTYPE_DRAW_FUNCTION_PROTO(012)
BOXTYPE_DRAW_FUNCTION_PROTO(013)
BOXTYPE_DRAW_FUNCTION_PROTO(014)
BOXTYPE_DRAW_FUNCTION_PROTO(015)
BOXTYPE_DRAW_FUNCTION_PROTO(016)
BOXTYPE_DRAW_FUNCTION_PROTO(017)
BOXTYPE_DRAW_FUNCTION_PROTO(018)
BOXTYPE_DRAW_FUNCTION_PROTO(019)
BOXTYPE_DRAW_FUNCTION_PROTO(020)
BOXTYPE_DRAW_FUNCTION_PROTO(021)
BOXTYPE_DRAW_FUNCTION_PROTO(022)
BOXTYPE_DRAW_FUNCTION_PROTO(023)
BOXTYPE_DRAW_FUNCTION_PROTO(024)
BOXTYPE_DRAW_FUNCTION_PROTO(025)
BOXTYPE_DRAW_FUNCTION_PROTO(026)
BOXTYPE_DRAW_FUNCTION_PROTO(027)
BOXTYPE_DRAW_FUNCTION_PROTO(028)
BOXTYPE_DRAW_FUNCTION_PROTO(029)
BOXTYPE_DRAW_FUNCTION_PROTO(030)
BOXTYPE_DRAW_FUNCTION_PROTO(031)
BOXTYPE_DRAW_FUNCTION_PROTO(032)
BOXTYPE_DRAW_FUNCTION_PROTO(033)
BOXTYPE_DRAW_FUNCTION_PROTO(034)
BOXTYPE_DRAW_FUNCTION_PROTO(035)
BOXTYPE_DRAW_FUNCTION_PROTO(036)
BOXTYPE_DRAW_FUNCTION_PROTO(037)
BOXTYPE_DRAW_FUNCTION_PROTO(038)
BOXTYPE_DRAW_FUNCTION_PROTO(039)
BOXTYPE_DRAW_FUNCTION_PROTO(040)
BOXTYPE_DRAW_FUNCTION_PROTO(041)
BOXTYPE_DRAW_FUNCTION_PROTO(042)
BOXTYPE_DRAW_FUNCTION_PROTO(043)
BOXTYPE_DRAW_FUNCTION_PROTO(044)
BOXTYPE_DRAW_FUNCTION_PROTO(045)
BOXTYPE_DRAW_FUNCTION_PROTO(046)
BOXTYPE_DRAW_FUNCTION_PROTO(047)
BOXTYPE_DRAW_FUNCTION_PROTO(048)
BOXTYPE_DRAW_FUNCTION_PROTO(049)
BOXTYPE_DRAW_FUNCTION_PROTO(050)
BOXTYPE_DRAW_FUNCTION_PROTO(051)
BOXTYPE_DRAW_FUNCTION_PROTO(052)
BOXTYPE_DRAW_FUNCTION_PROTO(053)
BOXTYPE_DRAW_FUNCTION_PROTO(054)
BOXTYPE_DRAW_FUNCTION_PROTO(055)
BOXTYPE_DRAW_FUNCTION_PROTO(056)
BOXTYPE_DRAW_FUNCTION_PROTO(057)
BOXTYPE_DRAW_FUNCTION_PROTO(058)
BOXTYPE_DRAW_FUNCTION_PROTO(059)
BOXTYPE_DRAW_FUNCTION_PROTO(060)
BOXTYPE_DRAW_FUNCTION_PROTO(061)
BOXTYPE_DRAW_FUNCTION_PROTO(062)
BOXTYPE_DRAW_FUNCTION_PROTO(063)
BOXTYPE_DRAW_FUNCTION_PROTO(064)
BOXTYPE_DRAW_FUNCTION_PROTO(065)
BOXTYPE_DRAW_FUNCTION_PROTO(066)
BOXTYPE_DRAW_FUNCTION_PROTO(067)
BOXTYPE_DRAW_FUNCTION_PROTO(068)
BOXTYPE_DRAW_FUNCTION_PROTO(069)
BOXTYPE_DRAW_FUNCTION_PROTO(070)
BOXTYPE_DRAW_FUNCTION_PROTO(071)
BOXTYPE_DRAW_FUNCTION_PROTO(072)
BOXTYPE_DRAW_FUNCTION_PROTO(073)
BOXTYPE_DRAW_FUNCTION_PROTO(074)
BOXTYPE_DRAW_FUNCTION_PROTO(075)
BOXTYPE_DRAW_FUNCTION_PROTO(076)
BOXTYPE_DRAW_FUNCTION_PROTO(077)
BOXTYPE_DRAW_FUNCTION_PROTO(078)
BOXTYPE_DRAW_FUNCTION_PROTO(079)
BOXTYPE_DRAW_FUNCTION_PROTO(080)
BOXTYPE_DRAW_FUNCTION_PROTO(081)
BOXTYPE_DRAW_FUNCTION_PROTO(082)
BOXTYPE_DRAW_FUNCTION_PROTO(083)
BOXTYPE_DRAW_FUNCTION_PROTO(084)
BOXTYPE_DRAW_FUNCTION_PROTO(085)
BOXTYPE_DRAW_FUNCTION_PROTO(086)
BOXTYPE_DRAW_FUNCTION_PROTO(087)
BOXTYPE_DRAW_FUNCTION_PROTO(088)
BOXTYPE_DRAW_FUNCTION_PROTO(089)
BOXTYPE_DRAW_FUNCTION_PROTO(090)
BOXTYPE_DRAW_FUNCTION_PROTO(091)
BOXTYPE_DRAW_FUNCTION_PROTO(092)
BOXTYPE_DRAW_FUNCTION_PROTO(093)
BOXTYPE_DRAW_FUNCTION_PROTO(094)
BOXTYPE_DRAW_FUNCTION_PROTO(095)
BOXTYPE_DRAW_FUNCTION_PROTO(096)
BOXTYPE_DRAW_FUNCTION_PROTO(097)
BOXTYPE_DRAW_FUNCTION_PROTO(098)
BOXTYPE_DRAW_FUNCTION_PROTO(099)
BOXTYPE_DRAW_FUNCTION_PROTO(100)
BOXTYPE_DRAW_FUNCTION_PROTO(101)
BOXTYPE_DRAW_FUNCTION_PROTO(102)
BOXTYPE_DRAW_FUNCTION_PROTO(103)
BOXTYPE_DRAW_FUNCTION_PROTO(104)
BOXTYPE_DRAW_FUNCTION_PROTO(105)
BOXTYPE_DRAW_FUNCTION_PROTO(106)
BOXTYPE_DRAW_FUNCTION_PROTO(107)
BOXTYPE_DRAW_FUNCTION_PROTO(108)
BOXTYPE_DRAW_FUNCTION_PROTO(109)
BOXTYPE_DRAW_FUNCTION_PROTO(110)
BOXTYPE_DRAW_FUNCTION_PROTO(111)
BOXTYPE_DRAW_FUNCTION_PROTO(112)
BOXTYPE_DRAW_FUNCTION_PROTO(113)
BOXTYPE_DRAW_FUNCTION_PROTO(114)
BOXTYPE_DRAW_FUNCTION_PROTO(115)
BOXTYPE_DRAW_FUNCTION_PROTO(116)
BOXTYPE_DRAW_FUNCTION_PROTO(117)
BOXTYPE_DRAW_FUNCTION_PROTO(118)
BOXTYPE_DRAW_FUNCTION_PROTO(119)
BOXTYPE_DRAW_FUNCTION_PROTO(120)
BOXTYPE_DRAW_FUNCTION_PROTO(121)
BOXTYPE_DRAW_FUNCTION_PROTO(122)
BOXTYPE_DRAW_FUNCTION_PROTO(123)
BOXTYPE_DRAW_FUNCTION_PROTO(124)
BOXTYPE_DRAW_FUNCTION_PROTO(125)
BOXTYPE_DRAW_FUNCTION_PROTO(126)
BOXTYPE_DRAW_FUNCTION_PROTO(127)
BOXTYPE_DRAW_FUNCTION_PROTO(128)
BOXTYPE_DRAW_FUNCTION_PROTO(129)
BOXTYPE_DRAW_FUNCTION_PROTO(130)
BOXTYPE_DRAW_FUNCTION_PROTO(131)
BOXTYPE_DRAW_FUNCTION_PROTO(132)
BOXTYPE_DRAW_FUNCTION_PROTO(133)
BOXTYPE_DRAW_FUNCTION_PROTO(134)
BOXTYPE_DRAW_FUNCTION_PROTO(135)
BOXTYPE_DRAW_FUNCTION_PROTO(136)
BOXTYPE_DRAW_FUNCTION_PROTO(137)
BOXTYPE_DRAW_FUNCTION_PROTO(138)
BOXTYPE_DRAW_FUNCTION_PROTO(139)
BOXTYPE_DRAW_FUNCTION_PROTO(140)
BOXTYPE_DRAW_FUNCTION_PROTO(141)
BOXTYPE_DRAW_FUNCTION_PROTO(142)
BOXTYPE_DRAW_FUNCTION_PROTO(143)
BOXTYPE_DRAW_FUNCTION_PROTO(144)
BOXTYPE_DRAW_FUNCTION_PROTO(145)
BOXTYPE_DRAW_FUNCTION_PROTO(146)
BOXTYPE_DRAW_FUNCTION_PROTO(147)
BOXTYPE_DRAW_FUNCTION_PROTO(148)
BOXTYPE_DRAW_FUNCTION_PROTO(149)
BOXTYPE_DRAW_FUNCTION_PROTO(150)
BOXTYPE_DRAW_FUNCTION_PROTO(151)
BOXTYPE_DRAW_FUNCTION_PROTO(152)
BOXTYPE_DRAW_FUNCTION_PROTO(153)
BOXTYPE_DRAW_FUNCTION_PROTO(154)
BOXTYPE_DRAW_FUNCTION_PROTO(155)
BOXTYPE_DRAW_FUNCTION_PROTO(156)
BOXTYPE_DRAW_FUNCTION_PROTO(157)
BOXTYPE_DRAW_FUNCTION_PROTO(158)
BOXTYPE_DRAW_FUNCTION_PROTO(159)
BOXTYPE_DRAW_FUNCTION_PROTO(160)
BOXTYPE_DRAW_FUNCTION_PROTO(161)
BOXTYPE_DRAW_FUNCTION_PROTO(162)
BOXTYPE_DRAW_FUNCTION_PROTO(163)
BOXTYPE_DRAW_FUNCTION_PROTO(164)
BOXTYPE_DRAW_FUNCTION_PROTO(165)
BOXTYPE_DRAW_FUNCTION_PROTO(166)
BOXTYPE_DRAW_FUNCTION_PROTO(167)
BOXTYPE_DRAW_FUNCTION_PROTO(168)
BOXTYPE_DRAW_FUNCTION_PROTO(169)
BOXTYPE_DRAW_FUNCTION_PROTO(170)
BOXTYPE_DRAW_FUNCTION_PROTO(171)
BOXTYPE_DRAW_FUNCTION_PROTO(172)
BOXTYPE_DRAW_FUNCTION_PROTO(173)
BOXTYPE_DRAW_FUNCTION_PROTO(174)
BOXTYPE_DRAW_FUNCTION_PROTO(175)
BOXTYPE_DRAW_FUNCTION_PROTO(176)
BOXTYPE_DRAW_FUNCTION_PROTO(177)
BOXTYPE_DRAW_FUNCTION_PROTO(178)
BOXTYPE_DRAW_FUNCTION_PROTO(179)
BOXTYPE_DRAW_FUNCTION_PROTO(180)
BOXTYPE_DRAW_FUNCTION_PROTO(181)
BOXTYPE_DRAW_FUNCTION_PROTO(182)
BOXTYPE_DRAW_FUNCTION_PROTO(183)
BOXTYPE_DRAW_FUNCTION_PROTO(184)
BOXTYPE_DRAW_FUNCTION_PROTO(185)
BOXTYPE_DRAW_FUNCTION_PROTO(186)
BOXTYPE_DRAW_FUNCTION_PROTO(187)
BOXTYPE_DRAW_FUNCTION_PROTO(188)
BOXTYPE_DRAW_FUNCTION_PROTO(189)
BOXTYPE_DRAW_FUNCTION_PROTO(190)
BOXTYPE_DRAW_FUNCTION_PROTO(191)
BOXTYPE_DRAW_FUNCTION_PROTO(192)
BOXTYPE_DRAW_FUNCTION_PROTO(193)
BOXTYPE_DRAW_FUNCTION_PROTO(194)
BOXTYPE_DRAW_FUNCTION_PROTO(195)
BOXTYPE_DRAW_FUNCTION_PROTO(196)
BOXTYPE_DRAW_FUNCTION_PROTO(197)
BOXTYPE_DRAW_FUNCTION_PROTO(198)
BOXTYPE_DRAW_FUNCTION_PROTO(199)
BOXTYPE_DRAW_FUNCTION_PROTO(200)
BOXTYPE_DRAW_FUNCTION_PROTO(201)
BOXTYPE_DRAW_FUNCTION_PROTO(202)
BOXTYPE_DRAW_FUNCTION_PROTO(203)
BOXTYPE_DRAW_FUNCTION_PROTO(204)
BOXTYPE_DRAW_FUNCTION_PROTO(205)
BOXTYPE_DRAW_FUNCTION_PROTO(206)
BOXTYPE_DRAW_FUNCTION_PROTO(207)
BOXTYPE_DRAW_FUNCTION_PROTO(208)
BOXTYPE_DRAW_FUNCTION_PROTO(209)
BOXTYPE_DRAW_FUNCTION_PROTO(210)
BOXTYPE_DRAW_FUNCTION_PROTO(211)
BOXTYPE_DRAW_FUNCTION_PROTO(212)
BOXTYPE_DRAW_FUNCTION_PROTO(213)
BOXTYPE_DRAW_FUNCTION_PROTO(214)
BOXTYPE_DRAW_FUNCTION_PROTO(215)
BOXTYPE_DRAW_FUNCTION_PROTO(216)
BOXTYPE_DRAW_FUNCTION_PROTO(217)
BOXTYPE_DRAW_FUNCTION_PROTO(218)
BOXTYPE_DRAW_FUNCTION_PROTO(219)
BOXTYPE_DRAW_FUNCTION_PROTO(220)
BOXTYPE_DRAW_FUNCTION_PROTO(221)
BOXTYPE_DRAW_FUNCTION_PROTO(222)
BOXTYPE_DRAW_FUNCTION_PROTO(223)
BOXTYPE_DRAW_FUNCTION_PROTO(224)
BOXTYPE_DRAW_FUNCTION_PROTO(225)
BOXTYPE_DRAW_FUNCTION_PROTO(226)
BOXTYPE_DRAW_FUNCTION_PROTO(227)
BOXTYPE_DRAW_FUNCTION_PROTO(228)
BOXTYPE_DRAW_FUNCTION_PROTO(229)
BOXTYPE_DRAW_FUNCTION_PROTO(230)
BOXTYPE_DRAW_FUNCTION_PROTO(231)
BOXTYPE_DRAW_FUNCTION_PROTO(232)
BOXTYPE_DRAW_FUNCTION_PROTO(233)
BOXTYPE_DRAW_FUNCTION_PROTO(234)
BOXTYPE_DRAW_FUNCTION_PROTO(235)
BOXTYPE_DRAW_FUNCTION_PROTO(236)
BOXTYPE_DRAW_FUNCTION_PROTO(237)
BOXTYPE_DRAW_FUNCTION_PROTO(238)
BOXTYPE_DRAW_FUNCTION_PROTO(239)
BOXTYPE_DRAW_FUNCTION_PROTO(240)
BOXTYPE_DRAW_FUNCTION_PROTO(241)
BOXTYPE_DRAW_FUNCTION_PROTO(242)
BOXTYPE_DRAW_FUNCTION_PROTO(243)
BOXTYPE_DRAW_FUNCTION_PROTO(244)
BOXTYPE_DRAW_FUNCTION_PROTO(245)
BOXTYPE_DRAW_FUNCTION_PROTO(246)
BOXTYPE_DRAW_FUNCTION_PROTO(247)
BOXTYPE_DRAW_FUNCTION_PROTO(248)
BOXTYPE_DRAW_FUNCTION_PROTO(249)
BOXTYPE_DRAW_FUNCTION_PROTO(250)
BOXTYPE_DRAW_FUNCTION_PROTO(251)
BOXTYPE_DRAW_FUNCTION_PROTO(252)
BOXTYPE_DRAW_FUNCTION_PROTO(253)
BOXTYPE_DRAW_FUNCTION_PROTO(254)
BOXTYPE_DRAW_FUNCTION_PROTO(255)
// } Prototypes

// ReferenceTable {
static Boxtype_FunctionRef boxtype_FunctionRefs[256] = {
    { LUA_NOREF, boxtypeDrawFunction000, NULL },
    { LUA_NOREF, boxtypeDrawFunction001, NULL },
    { LUA_NOREF, boxtypeDrawFunction002, NULL },
    { LUA_NOREF, boxtypeDrawFunction003, NULL },
    { LUA_NOREF, boxtypeDrawFunction004, NULL },
    { LUA_NOREF, boxtypeDrawFunction005, NULL },
    { LUA_NOREF, boxtypeDrawFunction006, NULL },
    { LUA_NOREF, boxtypeDrawFunction007, NULL },
    { LUA_NOREF, boxtypeDrawFunction008, NULL },
    { LUA_NOREF, boxtypeDrawFunction009, NULL },
    { LUA_NOREF, boxtypeDrawFunction010, NULL },
    { LUA_NOREF, boxtypeDrawFunction011, NULL },
    { LUA_NOREF, boxtypeDrawFunction012, NULL },
    { LUA_NOREF, boxtypeDrawFunction013, NULL },
    { LUA_NOREF, boxtypeDrawFunction014, NULL },
    { LUA_NOREF, boxtypeDrawFunction015, NULL },
    { LUA_NOREF, boxtypeDrawFunction016, NULL },
    { LUA_NOREF, boxtypeDrawFunction017, NULL },
    { LUA_NOREF, boxtypeDrawFunction018, NULL },
    { LUA_NOREF, boxtypeDrawFunction019, NULL },
    { LUA_NOREF, boxtypeDrawFunction020, NULL },
    { LUA_NOREF, boxtypeDrawFunction021, NULL },
    { LUA_NOREF, boxtypeDrawFunction022, NULL },
    { LUA_NOREF, boxtypeDrawFunction023, NULL },
    { LUA_NOREF, boxtypeDrawFunction024, NULL },
    { LUA_NOREF, boxtypeDrawFunction025, NULL },
    { LUA_NOREF, boxtypeDrawFunction026, NULL },
    { LUA_NOREF, boxtypeDrawFunction027, NULL },
    { LUA_NOREF, boxtypeDrawFunction028, NULL },
    { LUA_NOREF, boxtypeDrawFunction029, NULL },
    { LUA_NOREF, boxtypeDrawFunction030, NULL },
    { LUA_NOREF, boxtypeDrawFunction031, NULL },
    { LUA_NOREF, boxtypeDrawFunction032, NULL },
    { LUA_NOREF, boxtypeDrawFunction033, NULL },
    { LUA_NOREF, boxtypeDrawFunction034, NULL },
    { LUA_NOREF, boxtypeDrawFunction035, NULL },
    { LUA_NOREF, boxtypeDrawFunction036, NULL },
    { LUA_NOREF, boxtypeDrawFunction037, NULL },
    { LUA_NOREF, boxtypeDrawFunction038, NULL },
    { LUA_NOREF, boxtypeDrawFunction039, NULL },
    { LUA_NOREF, boxtypeDrawFunction040, NULL },
    { LUA_NOREF, boxtypeDrawFunction041, NULL },
    { LUA_NOREF, boxtypeDrawFunction042, NULL },
    { LUA_NOREF, boxtypeDrawFunction043, NULL },
    { LUA_NOREF, boxtypeDrawFunction044, NULL },
    { LUA_NOREF, boxtypeDrawFunction045, NULL },
    { LUA_NOREF, boxtypeDrawFunction046, NULL },
    { LUA_NOREF, boxtypeDrawFunction047, NULL },
    { LUA_NOREF, boxtypeDrawFunction048, NULL },
    { LUA_NOREF, boxtypeDrawFunction049, NULL },
    { LUA_NOREF, boxtypeDrawFunction050, NULL },
    { LUA_NOREF, boxtypeDrawFunction051, NULL },
    { LUA_NOREF, boxtypeDrawFunction052, NULL },
    { LUA_NOREF, boxtypeDrawFunction053, NULL },
    { LUA_NOREF, boxtypeDrawFunction054, NULL },
    { LUA_NOREF, boxtypeDrawFunction055, NULL },
    { LUA_NOREF, boxtypeDrawFunction056, NULL },
    { LUA_NOREF, boxtypeDrawFunction057, NULL },
    { LUA_NOREF, boxtypeDrawFunction058, NULL },
    { LUA_NOREF, boxtypeDrawFunction059, NULL },
    { LUA_NOREF, boxtypeDrawFunction060, NULL },
    { LUA_NOREF, boxtypeDrawFunction061, NULL },
    { LUA_NOREF, boxtypeDrawFunction062, NULL },
    { LUA_NOREF, boxtypeDrawFunction063, NULL },
    { LUA_NOREF, boxtypeDrawFunction064, NULL },
    { LUA_NOREF, boxtypeDrawFunction065, NULL },
    { LUA_NOREF, boxtypeDrawFunction066, NULL },
    { LUA_NOREF, boxtypeDrawFunction067, NULL },
    { LUA_NOREF, boxtypeDrawFunction068, NULL },
    { LUA_NOREF, boxtypeDrawFunction069, NULL },
    { LUA_NOREF, boxtypeDrawFunction070, NULL },
    { LUA_NOREF, boxtypeDrawFunction071, NULL },
    { LUA_NOREF, boxtypeDrawFunction072, NULL },
    { LUA_NOREF, boxtypeDrawFunction073, NULL },
    { LUA_NOREF, boxtypeDrawFunction074, NULL },
    { LUA_NOREF, boxtypeDrawFunction075, NULL },
    { LUA_NOREF, boxtypeDrawFunction076, NULL },
    { LUA_NOREF, boxtypeDrawFunction077, NULL },
    { LUA_NOREF, boxtypeDrawFunction078, NULL },
    { LUA_NOREF, boxtypeDrawFunction079, NULL },
    { LUA_NOREF, boxtypeDrawFunction080, NULL },
    { LUA_NOREF, boxtypeDrawFunction081, NULL },
    { LUA_NOREF, boxtypeDrawFunction082, NULL },
    { LUA_NOREF, boxtypeDrawFunction083, NULL },
    { LUA_NOREF, boxtypeDrawFunction084, NULL },
    { LUA_NOREF, boxtypeDrawFunction085, NULL },
    { LUA_NOREF, boxtypeDrawFunction086, NULL },
    { LUA_NOREF, boxtypeDrawFunction087, NULL },
    { LUA_NOREF, boxtypeDrawFunction088, NULL },
    { LUA_NOREF, boxtypeDrawFunction089, NULL },
    { LUA_NOREF, boxtypeDrawFunction090, NULL },
    { LUA_NOREF, boxtypeDrawFunction091, NULL },
    { LUA_NOREF, boxtypeDrawFunction092, NULL },
    { LUA_NOREF, boxtypeDrawFunction093, NULL },
    { LUA_NOREF, boxtypeDrawFunction094, NULL },
    { LUA_NOREF, boxtypeDrawFunction095, NULL },
    { LUA_NOREF, boxtypeDrawFunction096, NULL },
    { LUA_NOREF, boxtypeDrawFunction097, NULL },
    { LUA_NOREF, boxtypeDrawFunction098, NULL },
    { LUA_NOREF, boxtypeDrawFunction099, NULL },
    { LUA_NOREF, boxtypeDrawFunction100, NULL },
    { LUA_NOREF, boxtypeDrawFunction101, NULL },
    { LUA_NOREF, boxtypeDrawFunction102, NULL },
    { LUA_NOREF, boxtypeDrawFunction103, NULL },
    { LUA_NOREF, boxtypeDrawFunction104, NULL },
    { LUA_NOREF, boxtypeDrawFunction105, NULL },
    { LUA_NOREF, boxtypeDrawFunction106, NULL },
    { LUA_NOREF, boxtypeDrawFunction107, NULL },
    { LUA_NOREF, boxtypeDrawFunction108, NULL },
    { LUA_NOREF, boxtypeDrawFunction109, NULL },
    { LUA_NOREF, boxtypeDrawFunction110, NULL },
    { LUA_NOREF, boxtypeDrawFunction111, NULL },
    { LUA_NOREF, boxtypeDrawFunction112, NULL },
    { LUA_NOREF, boxtypeDrawFunction113, NULL },
    { LUA_NOREF, boxtypeDrawFunction114, NULL },
    { LUA_NOREF, boxtypeDrawFunction115, NULL },
    { LUA_NOREF, boxtypeDrawFunction116, NULL },
    { LUA_NOREF, boxtypeDrawFunction117, NULL },
    { LUA_NOREF, boxtypeDrawFunction118, NULL },
    { LUA_NOREF, boxtypeDrawFunction119, NULL },
    { LUA_NOREF, boxtypeDrawFunction120, NULL },
    { LUA_NOREF, boxtypeDrawFunction121, NULL },
    { LUA_NOREF, boxtypeDrawFunction122, NULL },
    { LUA_NOREF, boxtypeDrawFunction123, NULL },
    { LUA_NOREF, boxtypeDrawFunction124, NULL },
    { LUA_NOREF, boxtypeDrawFunction125, NULL },
    { LUA_NOREF, boxtypeDrawFunction126, NULL },
    { LUA_NOREF, boxtypeDrawFunction127, NULL },
    { LUA_NOREF, boxtypeDrawFunction128, NULL },
    { LUA_NOREF, boxtypeDrawFunction129, NULL },
    { LUA_NOREF, boxtypeDrawFunction130, NULL },
    { LUA_NOREF, boxtypeDrawFunction131, NULL },
    { LUA_NOREF, boxtypeDrawFunction132, NULL },
    { LUA_NOREF, boxtypeDrawFunction133, NULL },
    { LUA_NOREF, boxtypeDrawFunction134, NULL },
    { LUA_NOREF, boxtypeDrawFunction135, NULL },
    { LUA_NOREF, boxtypeDrawFunction136, NULL },
    { LUA_NOREF, boxtypeDrawFunction137, NULL },
    { LUA_NOREF, boxtypeDrawFunction138, NULL },
    { LUA_NOREF, boxtypeDrawFunction139, NULL },
    { LUA_NOREF, boxtypeDrawFunction140, NULL },
    { LUA_NOREF, boxtypeDrawFunction141, NULL },
    { LUA_NOREF, boxtypeDrawFunction142, NULL },
    { LUA_NOREF, boxtypeDrawFunction143, NULL },
    { LUA_NOREF, boxtypeDrawFunction144, NULL },
    { LUA_NOREF, boxtypeDrawFunction145, NULL },
    { LUA_NOREF, boxtypeDrawFunction146, NULL },
    { LUA_NOREF, boxtypeDrawFunction147, NULL },
    { LUA_NOREF, boxtypeDrawFunction148, NULL },
    { LUA_NOREF, boxtypeDrawFunction149, NULL },
    { LUA_NOREF, boxtypeDrawFunction150, NULL },
    { LUA_NOREF, boxtypeDrawFunction151, NULL },
    { LUA_NOREF, boxtypeDrawFunction152, NULL },
    { LUA_NOREF, boxtypeDrawFunction153, NULL },
    { LUA_NOREF, boxtypeDrawFunction154, NULL },
    { LUA_NOREF, boxtypeDrawFunction155, NULL },
    { LUA_NOREF, boxtypeDrawFunction156, NULL },
    { LUA_NOREF, boxtypeDrawFunction157, NULL },
    { LUA_NOREF, boxtypeDrawFunction158, NULL },
    { LUA_NOREF, boxtypeDrawFunction159, NULL },
    { LUA_NOREF, boxtypeDrawFunction160, NULL },
    { LUA_NOREF, boxtypeDrawFunction161, NULL },
    { LUA_NOREF, boxtypeDrawFunction162, NULL },
    { LUA_NOREF, boxtypeDrawFunction163, NULL },
    { LUA_NOREF, boxtypeDrawFunction164, NULL },
    { LUA_NOREF, boxtypeDrawFunction165, NULL },
    { LUA_NOREF, boxtypeDrawFunction166, NULL },
    { LUA_NOREF, boxtypeDrawFunction167, NULL },
    { LUA_NOREF, boxtypeDrawFunction168, NULL },
    { LUA_NOREF, boxtypeDrawFunction169, NULL },
    { LUA_NOREF, boxtypeDrawFunction170, NULL },
    { LUA_NOREF, boxtypeDrawFunction171, NULL },
    { LUA_NOREF, boxtypeDrawFunction172, NULL },
    { LUA_NOREF, boxtypeDrawFunction173, NULL },
    { LUA_NOREF, boxtypeDrawFunction174, NULL },
    { LUA_NOREF, boxtypeDrawFunction175, NULL },
    { LUA_NOREF, boxtypeDrawFunction176, NULL },
    { LUA_NOREF, boxtypeDrawFunction177, NULL },
    { LUA_NOREF, boxtypeDrawFunction178, NULL },
    { LUA_NOREF, boxtypeDrawFunction179, NULL },
    { LUA_NOREF, boxtypeDrawFunction180, NULL },
    { LUA_NOREF, boxtypeDrawFunction181, NULL },
    { LUA_NOREF, boxtypeDrawFunction182, NULL },
    { LUA_NOREF, boxtypeDrawFunction183, NULL },
    { LUA_NOREF, boxtypeDrawFunction184, NULL },
    { LUA_NOREF, boxtypeDrawFunction185, NULL },
    { LUA_NOREF, boxtypeDrawFunction186, NULL },
    { LUA_NOREF, boxtypeDrawFunction187, NULL },
    { LUA_NOREF, boxtypeDrawFunction188, NULL },
    { LUA_NOREF, boxtypeDrawFunction189, NULL },
    { LUA_NOREF, boxtypeDrawFunction190, NULL },
    { LUA_NOREF, boxtypeDrawFunction191, NULL },
    { LUA_NOREF, boxtypeDrawFunction192, NULL },
    { LUA_NOREF, boxtypeDrawFunction193, NULL },
    { LUA_NOREF, boxtypeDrawFunction194, NULL },
    { LUA_NOREF, boxtypeDrawFunction195, NULL },
    { LUA_NOREF, boxtypeDrawFunction196, NULL },
    { LUA_NOREF, boxtypeDrawFunction197, NULL },
    { LUA_NOREF, boxtypeDrawFunction198, NULL },
    { LUA_NOREF, boxtypeDrawFunction199, NULL },
    { LUA_NOREF, boxtypeDrawFunction200, NULL },
    { LUA_NOREF, boxtypeDrawFunction201, NULL },
    { LUA_NOREF, boxtypeDrawFunction202, NULL },
    { LUA_NOREF, boxtypeDrawFunction203, NULL },
    { LUA_NOREF, boxtypeDrawFunction204, NULL },
    { LUA_NOREF, boxtypeDrawFunction205, NULL },
    { LUA_NOREF, boxtypeDrawFunction206, NULL },
    { LUA_NOREF, boxtypeDrawFunction207, NULL },
    { LUA_NOREF, boxtypeDrawFunction208, NULL },
    { LUA_NOREF, boxtypeDrawFunction209, NULL },
    { LUA_NOREF, boxtypeDrawFunction210, NULL },
    { LUA_NOREF, boxtypeDrawFunction211, NULL },
    { LUA_NOREF, boxtypeDrawFunction212, NULL },
    { LUA_NOREF, boxtypeDrawFunction213, NULL },
    { LUA_NOREF, boxtypeDrawFunction214, NULL },
    { LUA_NOREF, boxtypeDrawFunction215, NULL },
    { LUA_NOREF, boxtypeDrawFunction216, NULL },
    { LUA_NOREF, boxtypeDrawFunction217, NULL },
    { LUA_NOREF, boxtypeDrawFunction218, NULL },
    { LUA_NOREF, boxtypeDrawFunction219, NULL },
    { LUA_NOREF, boxtypeDrawFunction220, NULL },
    { LUA_NOREF, boxtypeDrawFunction221, NULL },
    { LUA_NOREF, boxtypeDrawFunction222, NULL },
    { LUA_NOREF, boxtypeDrawFunction223, NULL },
    { LUA_NOREF, boxtypeDrawFunction224, NULL },
    { LUA_NOREF, boxtypeDrawFunction225, NULL },
    { LUA_NOREF, boxtypeDrawFunction226, NULL },
    { LUA_NOREF, boxtypeDrawFunction227, NULL },
    { LUA_NOREF, boxtypeDrawFunction228, NULL },
    { LUA_NOREF, boxtypeDrawFunction229, NULL },
    { LUA_NOREF, boxtypeDrawFunction230, NULL },
    { LUA_NOREF, boxtypeDrawFunction231, NULL },
    { LUA_NOREF, boxtypeDrawFunction232, NULL },
    { LUA_NOREF, boxtypeDrawFunction233, NULL },
    { LUA_NOREF, boxtypeDrawFunction234, NULL },
    { LUA_NOREF, boxtypeDrawFunction235, NULL },
    { LUA_NOREF, boxtypeDrawFunction236, NULL },
    { LUA_NOREF, boxtypeDrawFunction237, NULL },
    { LUA_NOREF, boxtypeDrawFunction238, NULL },
    { LUA_NOREF, boxtypeDrawFunction239, NULL },
    { LUA_NOREF, boxtypeDrawFunction240, NULL },
    { LUA_NOREF, boxtypeDrawFunction241, NULL },
    { LUA_NOREF, boxtypeDrawFunction242, NULL },
    { LUA_NOREF, boxtypeDrawFunction243, NULL },
    { LUA_NOREF, boxtypeDrawFunction244, NULL },
    { LUA_NOREF, boxtypeDrawFunction245, NULL },
    { LUA_NOREF, boxtypeDrawFunction246, NULL },
    { LUA_NOREF, boxtypeDrawFunction247, NULL },
    { LUA_NOREF, boxtypeDrawFunction248, NULL },
    { LUA_NOREF, boxtypeDrawFunction249, NULL },
    { LUA_NOREF, boxtypeDrawFunction250, NULL },
    { LUA_NOREF, boxtypeDrawFunction251, NULL },
    { LUA_NOREF, boxtypeDrawFunction252, NULL },
    { LUA_NOREF, boxtypeDrawFunction253, NULL },
    { LUA_NOREF, boxtypeDrawFunction254, NULL },
    { LUA_NOREF, boxtypeDrawFunction255, NULL }
}; // } ReferenceTable

// Implementations {
BOXTYPE_DRAW_FUNCTION_IMPL(000)
BOXTYPE_DRAW_FUNCTION_IMPL(001)
BOXTYPE_DRAW_FUNCTION_IMPL(002)
BOXTYPE_DRAW_FUNCTION_IMPL(003)
BOXTYPE_DRAW_FUNCTION_IMPL(004)
BOXTYPE_DRAW_FUNCTION_IMPL(005)
BOXTYPE_DRAW_FUNCTION_IMPL(006)
BOXTYPE_DRAW_FUNCTION_IMPL(007)
BOXTYPE_DRAW_FUNCTION_IMPL(008)
BOXTYPE_DRAW_FUNCTION_IMPL(009)
BOXTYPE_DRAW_FUNCTION_IMPL(010)
BOXTYPE_DRAW_FUNCTION_IMPL(011)
BOXTYPE_DRAW_FUNCTION_IMPL(012)
BOXTYPE_DRAW_FUNCTION_IMPL(013)
BOXTYPE_DRAW_FUNCTION_IMPL(014)
BOXTYPE_DRAW_FUNCTION_IMPL(015)
BOXTYPE_DRAW_FUNCTION_IMPL(016)
BOXTYPE_DRAW_FUNCTION_IMPL(017)
BOXTYPE_DRAW_FUNCTION_IMPL(018)
BOXTYPE_DRAW_FUNCTION_IMPL(019)
BOXTYPE_DRAW_FUNCTION_IMPL(020)
BOXTYPE_DRAW_FUNCTION_IMPL(021)
BOXTYPE_DRAW_FUNCTION_IMPL(022)
BOXTYPE_DRAW_FUNCTION_IMPL(023)
BOXTYPE_DRAW_FUNCTION_IMPL(024)
BOXTYPE_DRAW_FUNCTION_IMPL(025)
BOXTYPE_DRAW_FUNCTION_IMPL(026)
BOXTYPE_DRAW_FUNCTION_IMPL(027)
BOXTYPE_DRAW_FUNCTION_IMPL(028)
BOXTYPE_DRAW_FUNCTION_IMPL(029)
BOXTYPE_DRAW_FUNCTION_IMPL(030)
BOXTYPE_DRAW_FUNCTION_IMPL(031)
BOXTYPE_DRAW_FUNCTION_IMPL(032)
BOXTYPE_DRAW_FUNCTION_IMPL(033)
BOXTYPE_DRAW_FUNCTION_IMPL(034)
BOXTYPE_DRAW_FUNCTION_IMPL(035)
BOXTYPE_DRAW_FUNCTION_IMPL(036)
BOXTYPE_DRAW_FUNCTION_IMPL(037)
BOXTYPE_DRAW_FUNCTION_IMPL(038)
BOXTYPE_DRAW_FUNCTION_IMPL(039)
BOXTYPE_DRAW_FUNCTION_IMPL(040)
BOXTYPE_DRAW_FUNCTION_IMPL(041)
BOXTYPE_DRAW_FUNCTION_IMPL(042)
BOXTYPE_DRAW_FUNCTION_IMPL(043)
BOXTYPE_DRAW_FUNCTION_IMPL(044)
BOXTYPE_DRAW_FUNCTION_IMPL(045)
BOXTYPE_DRAW_FUNCTION_IMPL(046)
BOXTYPE_DRAW_FUNCTION_IMPL(047)
BOXTYPE_DRAW_FUNCTION_IMPL(048)
BOXTYPE_DRAW_FUNCTION_IMPL(049)
BOXTYPE_DRAW_FUNCTION_IMPL(050)
BOXTYPE_DRAW_FUNCTION_IMPL(051)
BOXTYPE_DRAW_FUNCTION_IMPL(052)
BOXTYPE_DRAW_FUNCTION_IMPL(053)
BOXTYPE_DRAW_FUNCTION_IMPL(054)
BOXTYPE_DRAW_FUNCTION_IMPL(055)
BOXTYPE_DRAW_FUNCTION_IMPL(056)
BOXTYPE_DRAW_FUNCTION_IMPL(057)
BOXTYPE_DRAW_FUNCTION_IMPL(058)
BOXTYPE_DRAW_FUNCTION_IMPL(059)
BOXTYPE_DRAW_FUNCTION_IMPL(060)
BOXTYPE_DRAW_FUNCTION_IMPL(061)
BOXTYPE_DRAW_FUNCTION_IMPL(062)
BOXTYPE_DRAW_FUNCTION_IMPL(063)
BOXTYPE_DRAW_FUNCTION_IMPL(064)
BOXTYPE_DRAW_FUNCTION_IMPL(065)
BOXTYPE_DRAW_FUNCTION_IMPL(066)
BOXTYPE_DRAW_FUNCTION_IMPL(067)
BOXTYPE_DRAW_FUNCTION_IMPL(068)
BOXTYPE_DRAW_FUNCTION_IMPL(069)
BOXTYPE_DRAW_FUNCTION_IMPL(070)
BOXTYPE_DRAW_FUNCTION_IMPL(071)
BOXTYPE_DRAW_FUNCTION_IMPL(072)
BOXTYPE_DRAW_FUNCTION_IMPL(073)
BOXTYPE_DRAW_FUNCTION_IMPL(074)
BOXTYPE_DRAW_FUNCTION_IMPL(075)
BOXTYPE_DRAW_FUNCTION_IMPL(076)
BOXTYPE_DRAW_FUNCTION_IMPL(077)
BOXTYPE_DRAW_FUNCTION_IMPL(078)
BOXTYPE_DRAW_FUNCTION_IMPL(079)
BOXTYPE_DRAW_FUNCTION_IMPL(080)
BOXTYPE_DRAW_FUNCTION_IMPL(081)
BOXTYPE_DRAW_FUNCTION_IMPL(082)
BOXTYPE_DRAW_FUNCTION_IMPL(083)
BOXTYPE_DRAW_FUNCTION_IMPL(084)
BOXTYPE_DRAW_FUNCTION_IMPL(085)
BOXTYPE_DRAW_FUNCTION_IMPL(086)
BOXTYPE_DRAW_FUNCTION_IMPL(087)
BOXTYPE_DRAW_FUNCTION_IMPL(088)
BOXTYPE_DRAW_FUNCTION_IMPL(089)
BOXTYPE_DRAW_FUNCTION_IMPL(090)
BOXTYPE_DRAW_FUNCTION_IMPL(091)
BOXTYPE_DRAW_FUNCTION_IMPL(092)
BOXTYPE_DRAW_FUNCTION_IMPL(093)
BOXTYPE_DRAW_FUNCTION_IMPL(094)
BOXTYPE_DRAW_FUNCTION_IMPL(095)
BOXTYPE_DRAW_FUNCTION_IMPL(096)
BOXTYPE_DRAW_FUNCTION_IMPL(097)
BOXTYPE_DRAW_FUNCTION_IMPL(098)
BOXTYPE_DRAW_FUNCTION_IMPL(099)
BOXTYPE_DRAW_FUNCTION_IMPL(100)
BOXTYPE_DRAW_FUNCTION_IMPL(101)
BOXTYPE_DRAW_FUNCTION_IMPL(102)
BOXTYPE_DRAW_FUNCTION_IMPL(103)
BOXTYPE_DRAW_FUNCTION_IMPL(104)
BOXTYPE_DRAW_FUNCTION_IMPL(105)
BOXTYPE_DRAW_FUNCTION_IMPL(106)
BOXTYPE_DRAW_FUNCTION_IMPL(107)
BOXTYPE_DRAW_FUNCTION_IMPL(108)
BOXTYPE_DRAW_FUNCTION_IMPL(109)
BOXTYPE_DRAW_FUNCTION_IMPL(110)
BOXTYPE_DRAW_FUNCTION_IMPL(111)
BOXTYPE_DRAW_FUNCTION_IMPL(112)
BOXTYPE_DRAW_FUNCTION_IMPL(113)
BOXTYPE_DRAW_FUNCTION_IMPL(114)
BOXTYPE_DRAW_FUNCTION_IMPL(115)
BOXTYPE_DRAW_FUNCTION_IMPL(116)
BOXTYPE_DRAW_FUNCTION_IMPL(117)
BOXTYPE_DRAW_FUNCTION_IMPL(118)
BOXTYPE_DRAW_FUNCTION_IMPL(119)
BOXTYPE_DRAW_FUNCTION_IMPL(120)
BOXTYPE_DRAW_FUNCTION_IMPL(121)
BOXTYPE_DRAW_FUNCTION_IMPL(122)
BOXTYPE_DRAW_FUNCTION_IMPL(123)
BOXTYPE_DRAW_FUNCTION_IMPL(124)
BOXTYPE_DRAW_FUNCTION_IMPL(125)
BOXTYPE_DRAW_FUNCTION_IMPL(126)
BOXTYPE_DRAW_FUNCTION_IMPL(127)
BOXTYPE_DRAW_FUNCTION_IMPL(128)
BOXTYPE_DRAW_FUNCTION_IMPL(129)
BOXTYPE_DRAW_FUNCTION_IMPL(130)
BOXTYPE_DRAW_FUNCTION_IMPL(131)
BOXTYPE_DRAW_FUNCTION_IMPL(132)
BOXTYPE_DRAW_FUNCTION_IMPL(133)
BOXTYPE_DRAW_FUNCTION_IMPL(134)
BOXTYPE_DRAW_FUNCTION_IMPL(135)
BOXTYPE_DRAW_FUNCTION_IMPL(136)
BOXTYPE_DRAW_FUNCTION_IMPL(137)
BOXTYPE_DRAW_FUNCTION_IMPL(138)
BOXTYPE_DRAW_FUNCTION_IMPL(139)
BOXTYPE_DRAW_FUNCTION_IMPL(140)
BOXTYPE_DRAW_FUNCTION_IMPL(141)
BOXTYPE_DRAW_FUNCTION_IMPL(142)
BOXTYPE_DRAW_FUNCTION_IMPL(143)
BOXTYPE_DRAW_FUNCTION_IMPL(144)
BOXTYPE_DRAW_FUNCTION_IMPL(145)
BOXTYPE_DRAW_FUNCTION_IMPL(146)
BOXTYPE_DRAW_FUNCTION_IMPL(147)
BOXTYPE_DRAW_FUNCTION_IMPL(148)
BOXTYPE_DRAW_FUNCTION_IMPL(149)
BOXTYPE_DRAW_FUNCTION_IMPL(150)
BOXTYPE_DRAW_FUNCTION_IMPL(151)
BOXTYPE_DRAW_FUNCTION_IMPL(152)
BOXTYPE_DRAW_FUNCTION_IMPL(153)
BOXTYPE_DRAW_FUNCTION_IMPL(154)
BOXTYPE_DRAW_FUNCTION_IMPL(155)
BOXTYPE_DRAW_FUNCTION_IMPL(156)
BOXTYPE_DRAW_FUNCTION_IMPL(157)
BOXTYPE_DRAW_FUNCTION_IMPL(158)
BOXTYPE_DRAW_FUNCTION_IMPL(159)
BOXTYPE_DRAW_FUNCTION_IMPL(160)
BOXTYPE_DRAW_FUNCTION_IMPL(161)
BOXTYPE_DRAW_FUNCTION_IMPL(162)
BOXTYPE_DRAW_FUNCTION_IMPL(163)
BOXTYPE_DRAW_FUNCTION_IMPL(164)
BOXTYPE_DRAW_FUNCTION_IMPL(165)
BOXTYPE_DRAW_FUNCTION_IMPL(166)
BOXTYPE_DRAW_FUNCTION_IMPL(167)
BOXTYPE_DRAW_FUNCTION_IMPL(168)
BOXTYPE_DRAW_FUNCTION_IMPL(169)
BOXTYPE_DRAW_FUNCTION_IMPL(170)
BOXTYPE_DRAW_FUNCTION_IMPL(171)
BOXTYPE_DRAW_FUNCTION_IMPL(172)
BOXTYPE_DRAW_FUNCTION_IMPL(173)
BOXTYPE_DRAW_FUNCTION_IMPL(174)
BOXTYPE_DRAW_FUNCTION_IMPL(175)
BOXTYPE_DRAW_FUNCTION_IMPL(176)
BOXTYPE_DRAW_FUNCTION_IMPL(177)
BOXTYPE_DRAW_FUNCTION_IMPL(178)
BOXTYPE_DRAW_FUNCTION_IMPL(179)
BOXTYPE_DRAW_FUNCTION_IMPL(180)
BOXTYPE_DRAW_FUNCTION_IMPL(181)
BOXTYPE_DRAW_FUNCTION_IMPL(182)
BOXTYPE_DRAW_FUNCTION_IMPL(183)
BOXTYPE_DRAW_FUNCTION_IMPL(184)
BOXTYPE_DRAW_FUNCTION_IMPL(185)
BOXTYPE_DRAW_FUNCTION_IMPL(186)
BOXTYPE_DRAW_FUNCTION_IMPL(187)
BOXTYPE_DRAW_FUNCTION_IMPL(188)
BOXTYPE_DRAW_FUNCTION_IMPL(189)
BOXTYPE_DRAW_FUNCTION_IMPL(190)
BOXTYPE_DRAW_FUNCTION_IMPL(191)
BOXTYPE_DRAW_FUNCTION_IMPL(192)
BOXTYPE_DRAW_FUNCTION_IMPL(193)
BOXTYPE_DRAW_FUNCTION_IMPL(194)
BOXTYPE_DRAW_FUNCTION_IMPL(195)
BOXTYPE_DRAW_FUNCTION_IMPL(196)
BOXTYPE_DRAW_FUNCTION_IMPL(197)
BOXTYPE_DRAW_FUNCTION_IMPL(198)
BOXTYPE_DRAW_FUNCTION_IMPL(199)
BOXTYPE_DRAW_FUNCTION_IMPL(200)
BOXTYPE_DRAW_FUNCTION_IMPL(201)
BOXTYPE_DRAW_FUNCTION_IMPL(202)
BOXTYPE_DRAW_FUNCTION_IMPL(203)
BOXTYPE_DRAW_FUNCTION_IMPL(204)
BOXTYPE_DRAW_FUNCTION_IMPL(205)
BOXTYPE_DRAW_FUNCTION_IMPL(206)
BOXTYPE_DRAW_FUNCTION_IMPL(207)
BOXTYPE_DRAW_FUNCTION_IMPL(208)
BOXTYPE_DRAW_FUNCTION_IMPL(209)
BOXTYPE_DRAW_FUNCTION_IMPL(210)
BOXTYPE_DRAW_FUNCTION_IMPL(211)
BOXTYPE_DRAW_FUNCTION_IMPL(212)
BOXTYPE_DRAW_FUNCTION_IMPL(213)
BOXTYPE_DRAW_FUNCTION_IMPL(214)
BOXTYPE_DRAW_FUNCTION_IMPL(215)
BOXTYPE_DRAW_FUNCTION_IMPL(216)
BOXTYPE_DRAW_FUNCTION_IMPL(217)
BOXTYPE_DRAW_FUNCTION_IMPL(218)
BOXTYPE_DRAW_FUNCTION_IMPL(219)
BOXTYPE_DRAW_FUNCTION_IMPL(220)
BOXTYPE_DRAW_FUNCTION_IMPL(221)
BOXTYPE_DRAW_FUNCTION_IMPL(222)
BOXTYPE_DRAW_FUNCTION_IMPL(223)
BOXTYPE_DRAW_FUNCTION_IMPL(224)
BOXTYPE_DRAW_FUNCTION_IMPL(225)
BOXTYPE_DRAW_FUNCTION_IMPL(226)
BOXTYPE_DRAW_FUNCTION_IMPL(227)
BOXTYPE_DRAW_FUNCTION_IMPL(228)
BOXTYPE_DRAW_FUNCTION_IMPL(229)
BOXTYPE_DRAW_FUNCTION_IMPL(230)
BOXTYPE_DRAW_FUNCTION_IMPL(231)
BOXTYPE_DRAW_FUNCTION_IMPL(232)
BOXTYPE_DRAW_FUNCTION_IMPL(233)
BOXTYPE_DRAW_FUNCTION_IMPL(234)
BOXTYPE_DRAW_FUNCTION_IMPL(235)
BOXTYPE_DRAW_FUNCTION_IMPL(236)
BOXTYPE_DRAW_FUNCTION_IMPL(237)
BOXTYPE_DRAW_FUNCTION_IMPL(238)
BOXTYPE_DRAW_FUNCTION_IMPL(239)
BOXTYPE_DRAW_FUNCTION_IMPL(240)
BOXTYPE_DRAW_FUNCTION_IMPL(241)
BOXTYPE_DRAW_FUNCTION_IMPL(242)
BOXTYPE_DRAW_FUNCTION_IMPL(243)
BOXTYPE_DRAW_FUNCTION_IMPL(244)
BOXTYPE_DRAW_FUNCTION_IMPL(245)
BOXTYPE_DRAW_FUNCTION_IMPL(246)
BOXTYPE_DRAW_FUNCTION_IMPL(247)
BOXTYPE_DRAW_FUNCTION_IMPL(248)
BOXTYPE_DRAW_FUNCTION_IMPL(249)
BOXTYPE_DRAW_FUNCTION_IMPL(250)
BOXTYPE_DRAW_FUNCTION_IMPL(251)
BOXTYPE_DRAW_FUNCTION_IMPL(252)
BOXTYPE_DRAW_FUNCTION_IMPL(253)
BOXTYPE_DRAW_FUNCTION_IMPL(254)
BOXTYPE_DRAW_FUNCTION_IMPL(255)
// } Implementations
